[tool.black]
line-length = 79
target-version = ['py312']
skip-string-normalization = true
extend-exclude = """
/(
|  venv
|  designs
)/
"""

[tool.ruff]
line-length = 79
indent-width = 4
target-version = "py312"

[tool.ruff.format]
quote-style = "single"
skip-magic-trailing-comma = true
# be careful with ruff's format as it
# ruins any nests without trailing commas

[tool.ruff.lint]
flake8-quotes.inline-quotes = "single"
flake8-tidy-imports.ban-relative-imports = "all"
select = ["E4", "E7", "E9", "F", "E501", "COM812", "Q000"]
exclude = ["venv", "designs/*"]

[tool.isort]
profile = "google"
force_sort_within_sections = true
force_alphabetical_sort_within_sections = true
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY",
    "LOCALABSOLUTE", "LOCALFOLDER"]
known_localabsolute = ["server", "designs", "client"]
no_lines_before = ["LOCALFOLDER"]
